### ISSUE TITLE
API registration fails for GDM systems

### ISSUE THREAD

**Issue by brendandobbs** [SAP/xf-addons#12]
APIs are active on the GDM Marketing system (accessible by Postman/curl). During registration the registration job outputs that the APIs are inactive.

The GDM systems have a reverse proxy configured which is the likely cause.

**Comment by brendandobbs** [comment]
The issue is that the GDM systems are using a reverse proxy. If the API URLs don't end with a '/' then the reverse proxy is redirecting to the same URL with a trailing slash. For an unknown reason the go HTTP client is not able to follow the redirect (500 error).

**Comment by a-thaler** [comment]
Fixed by https://github.com/kyma-incubator/connector-tools/pull/4
